const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const src=fs.readFileSync(process.argv[2]||'work/cart-check.mjs','utf8');
function fn(name,next){return src.slice(src.indexOf('    async function '+name+'('),src.indexOf(next,src.indexOf('    async function '+name+'(')))}
const inquiries=new Map();let inserts=0, fail=false;
const DB={prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){if(sql.includes('sqlite_master'))return null;if(sql.includes('FROM inquiries'))return inquiries.get(args[0])||null;return null},async run(){if(sql.includes('INSERT OR IGNORE INTO inquiries')){if(fail)return {success:false};const [id,source,name,email,phone,company,subject,message]=args;if(inquiries.has(id))return {success:true,meta:{changes:0}};inserts++;inquiries.set(id,{name,email,phone,company,subject,message});return {success:true,meta:{changes:1}}}return {success:true}},async all(){return {success:true,results:[]}}}}};
let logged=true;
const product={id:'p1',name:'Test',unit:'Kg',min_order_qty:.5,qty_step:.25};
const ctx={Request,Response,URL,TextEncoder,crypto:webcrypto,console,Date,Map,Set,ACTIVE_PRODUCT_CATALOG:[product],SEAFOOD_B2B_QUOTE_CATALOG:[],responseJSON:(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json'}}),memberSession:async()=>logged?{user_id:'u1',business_id:'b1'}:null,memberSHA:async s=>Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex'),commerceRoute:async()=>new Response(JSON.stringify({products:[product]})),memberD1All:async()=>({results:[]})};
vm.createContext(ctx);vm.runInContext(fn('okyContactMessageAPI','    /* ==========================================================================')+'\n'+fn('memberCommerceQuoteAPI','    async function quoteAPI('),ctx);
const body={customer:{name:'Test User',business:'Test Ltd',phone:'05351234567',email:'test@example.com'},products:[{id:'p1',quantity:.75,unit:'Kg'}],consent:{kvkk:true},idempotencyKey:'abcdefghijklmnop'};
const req=b=>new Request('https://example.test/api/quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});
(async()=>{
 let r=await ctx.memberCommerceQuoteAPI(req(body),{DB,ADMIN_DB:DB}),j=await r.json();assert.equal(r.status,201);assert(j.ok&&j.quoteNo&&j.id);const first=j;
 r=await ctx.memberCommerceQuoteAPI(req(body),{DB,ADMIN_DB:DB});j=await r.json();assert.equal(r.status,200);assert(j.duplicate);assert.equal(j.id,first.id);assert.equal(j.quoteNo,first.quoteNo);assert.equal(inserts,1);
 r=await ctx.memberCommerceQuoteAPI(req({...body,note:'changed'}),{DB,ADMIN_DB:DB});assert.equal(r.status,409);assert.equal(inserts,1);
 const concurrent={...body,idempotencyKey:'abcdefghijklmnop-concurrent'};const results=await Promise.all([ctx.memberCommerceQuoteAPI(req(concurrent),{DB,ADMIN_DB:DB}),ctx.memberCommerceQuoteAPI(req(concurrent),{DB,ADMIN_DB:DB})]);assert.deepEqual(results.map(x=>x.status).sort(),[200,201]);assert.equal(inserts,2);
 r=await ctx.memberCommerceQuoteAPI(req({...body,idempotencyKey:'other-valid-key-123',products:[{id:'p1',quantity:.6,unit:'Kg'}]}),{DB,ADMIN_DB:DB});assert.equal(r.status,400);
 logged=false;r=await ctx.memberCommerceQuoteAPI(req(body),{DB,ADMIN_DB:DB});assert.equal(r.status,401);logged=true;
 fail=true;r=await ctx.memberCommerceQuoteAPI(req({...body,idempotencyKey:'new-failure-key-123'}),{DB,ADMIN_DB:DB});assert.equal(r.status,503);assert.equal(inserts,2);fail=false;
 r=await ctx.memberCommerceQuoteAPI(req({...body,note:'x'.repeat(100001)}),{DB,ADMIN_DB:DB});assert.equal(r.status,413);
 // Render then parse actual browser template, not just server source.
 const cartStart=src.indexOf('function commerceCartPage(){'),cartEnd=src.indexOf('function commerceProductPage(',cartStart);let script='';const render={contactStrip:()=>'',html:x=>x,commerceClientShell:(_t,_b,s)=>{script=s;return s}};vm.createContext(render);vm.runInContext(src.slice(cartStart,cartEnd),render);render.commerceCartPage();new vm.Script(script);
 // Execute helper functions extracted from rendered code with real in-memory localStorage.
 const values=new Map(),localStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},math=script.slice(script.indexOf(' const round='),script.indexOf(' function slug('));const helper={localStorage,document:{dispatchEvent(){}},Event:class{},Map,Math,Number,JSON};vm.createContext(helper);vm.runInContext("const K='oky-commerce-cart-v2';\n"+math+'\nthis.quantity=qty;this.readCart=read;this.writeCart=write;',helper);assert.equal(helper.quantity(Infinity,product),.5);assert.equal(helper.quantity(.6,product),.5);assert.equal(helper.quantity(.9,product),1);helper.writeCart([{id:'p1',name:'Test',qty:.75,min_order_qty:.5,qty_step:.25}]);assert.equal(helper.readCart()[0].qty,.75);
 const element=()=>({innerHTML:'',textContent:'',className:'',disabled:false,elements:{namedItem:()=>null},addEventListener(){},reset(){}});const ui={cr:element(),cartSummary:element(),qSubmit:element(),cartStatus:element(),clearCart:element(),qr:element(),qf:element()};let sessionCalls=0,release;const pending=new Promise(resolve=>release=resolve);const store=new Map([['oky-commerce-cart-v2',JSON.stringify([{id:'p1',name:'Test',qty:.75,min_order_qty:.5,qty_step:.25,unit:'Kg'}])]]);const browser={...ui,window:{okyAccountReady:Promise.resolve(null)},location:{href:''},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},document:{addEventListener(){},dispatchEvent(){}},crypto:webcrypto,Event:class{},FormData:class{constructor(){return [['name','Test User'],['business','Test Ltd'],['phone','05351234567'],['email','test@example.com']][Symbol.iterator]()}},fetch:async url=>{if(url==='/api/member/me'){sessionCalls++;return pending}return new Response(JSON.stringify({products:[]}))},Intl,confirm:()=>false};vm.createContext(browser);vm.runInContext(script,browser);const one=ui.qf.onsubmit({preventDefault(){}}),two=ui.qf.onsubmit({preventDefault(){}});await Promise.resolve();await two;assert.equal(sessionCalls,1);release(new Response(JSON.stringify({ok:false}),{status:503}));await one;assert(ui.qr.textContent.includes('Oturum kontrol edilemedi'));assert.equal(browser.location.href,'');assert.equal(JSON.parse(store.get('oky-commerce-cart-v2')).length,1);
 console.log('PASS: double-submit lock, session network error retains cart; 8 quote API cases + parsed browser script + quantity and persistence model');
})().catch(e=>{console.error(e);process.exit(1)});
