const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');const src=fs.readFileSync(process.argv[2]||'final/zaman.mjs','utf8');
const route=src.slice(src.indexOf(" if(resource==='image-upload'){"),src.indexOf(' if(resource==="product-featured"&&id){'));
let calls=[],statuses=[];const context={crypto:webcrypto,URL,TextDecoder,Uint8Array,Array,String,JSON,btoa:s=>Buffer.from(s,'binary').toString('base64'),j:(x,status=200)=>({status,...x}),canWrite:a=>a?.user?.role==='owner',fetch:async(url,opt={})=>{calls.push({url,opt});const status=statuses.shift()||200;return {status,ok:status>=200&&status<300}}};vm.createContext(context);vm.runInContext('async function handler(request,env,auth,headers){const resource="image-upload";'+route+'}',context);
const image=new Uint8Array([137,80,78,71,13,10,26,10,1,2]),file={size:image.length,arrayBuffer:async()=>image.buffer};const req=(f=file)=>({method:'POST',headers:new Headers(),formData:async()=>({get:()=>f})}),owner={user:{role:'owner'}},env={GITHUB_MEDIA_TOKEN:'test-token'};
(async()=>{let r=await context.handler(req(),env,{user:{role:'admin'}},{});assert.equal(r.status,403);assert.equal(calls.length,0);r=await context.handler(req(),{},owner,{});assert.equal(r.status,503);assert.equal(calls.length,0);
 const invalid={size:3,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer};r=await context.handler(req(invalid),env,owner,{});assert.equal(r.status,400);
 statuses=[200];r=await context.handler(req(),env,owner,{});assert.equal(r.status,200);assert(r.url.includes('.png'));assert.equal(calls.length,1);assert(!calls[0].opt.method);assert(!JSON.stringify(r).includes('test-token'));
 calls=[];statuses=[404,201];r=await context.handler(req(),env,owner,{});assert.equal(r.status,200);assert.equal(calls.length,2);assert.equal(calls[1].opt.method,'PUT');const payload=JSON.parse(calls[1].opt.body);assert.equal(payload.content,Buffer.from(image).toString('base64'));assert(payload.branch);
 calls=[];statuses=[403];r=await context.handler(req(),env,owner,{});assert.equal(r.status,502);assert.equal(calls.length,1);
 calls=[];statuses=[404,500,404];r=await context.handler(req(),env,owner,{});assert.equal(r.status,502);
 calls=[];statuses=[404,409,200];r=await context.handler(req(),env,owner,{});assert.equal(r.status,200);
 // Actual rendered inline upload function: only unconfigured Github falls back to existing storage.
 const inline=src.slice(src.indexOf('async function uploadImageToEditor(box){'),src.indexOf('const imageEditorBindings='));const input={value:'',disabled:false,dispatchEvent(){}},fileInput={files:[{...file,type:'image/png',name:'test.png'}],disabled:false},button={disabled:false,textContent:''},submit={disabled:false},form={dataset:{},querySelector:()=>submit},box={querySelector:k=>({'[data-image-url]':input,'[data-image-file]':fileInput,'[data-upload-image]':button}[k]),closest:()=>form,querySelectorAll:()=>[input,fileInput,button]};let inlineCalls=[];const browser={FormData:class{append(){}},Event:class{},optimizeUploadImage:async f=>f,csrfToken:()=> 'csrf',fetch:async(url,opt)=>{inlineCalls.push({url,opt});return new Response(JSON.stringify(url.includes('commerce-admin')?{ok:false,error:'MEDIA_STORAGE_NOT_CONFIGURED'}:{ok:true,url:'https://example.test/image.png'}),{status:url.includes('commerce-admin')?503:201})}};vm.createContext(browser);vm.runInContext(inline,browser);await browser.uploadImageToEditor(box);assert.equal(inlineCalls.length,2);assert.equal(inlineCalls[1].url,'/api/studio-media');assert.equal(inlineCalls[0].opt.headers['X-CSRF-Token'],'csrf');assert.equal(input.value,'https://example.test/image.png');assert.equal(button.disabled,false);assert.equal(submit.disabled,false);assert.equal(form.dataset.uploading,'0');
 inlineCalls=[];browser.fetch=async(url,opt)=>{inlineCalls.push({url,opt});return new Response(JSON.stringify({ok:false,error:'FORBIDDEN'}),{status:403})};await assert.rejects(browser.uploadImageToEditor(box),/FORBIDDEN/);assert.equal(inlineCalls.length,1);assert.equal(submit.disabled,false);
 console.log('PASS upload endpoint: owner, token, signature, existing no PUT, new PUT, GET/PUT failures, concurrency retry; inline fallback and error controls');
})().catch(e=>{console.error(e);process.exit(1)});
