const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const s=fs.readFileSync(process.argv[2],'utf8'),a=s.indexOf(" const popup=document.getElementById('campaignPopup')"),b=s.indexOf('\n})();`}',a),script='(function(){'+s.slice(a,b)+'})();';
function page({store=new Map(),window={},key='A',enabled='true',path='/',blocked=false,loading=false}={}){
 const events={},docEvents={},frames=[];let opens=0;const popup={dataset:{enabled,campaignKey:key},open:false,showModal(){opens++;this.open=true},close(){this.open=false;events.close?.()},removeAttribute(){this.open=false},addEventListener:(k,f)=>events[k]=f},button={},close={};
 const ctx={window,document:{readyState:loading?'loading':'complete',getElementById:id=>({campaignPopup:popup,campaignOpen:button,campaignClose:close}[id]),addEventListener:(k,f)=>docEvents[k]=f},sessionStorage:{getItem:k=>{if(blocked)throw Error('blocked');return store.get(k)},setItem:(k,v)=>{if(blocked)throw Error('blocked');store.set(k,v)}},location:{pathname:path},requestAnimationFrame:fn=>frames.push(fn)};vm.createContext(ctx);vm.runInContext(script,ctx);return {ctx,popup,button,close,events,docEvents,frames,opens:()=>opens,run:()=>frames.splice(0).forEach(fn=>fn()),repeat:()=>vm.runInContext(script,ctx)}
}
let store=new Map([['oky-campaign-dismissed:A','1']]),p=page({store,loading:true});assert.equal(p.opens(),0);assert.equal(p.frames.length,0);p.docEvents.DOMContentLoaded();assert.equal(p.opens(),0);p.run();assert.equal(p.opens(),1);p.close.onclick();assert(!p.popup.open);let reload=page({store});reload.run();assert.equal(reload.opens(),0);reload.button.onclick();assert.equal(reload.opens(),1);reload.events.cancel({preventDefault(){}});assert(!reload.popup.open);reload.button.onclick();reload.events.click({target:reload.popup});assert(!reload.popup.open);
p=page({store,key:'B'});p.run();assert.equal(p.opens(),1);for(const options of [{enabled:'false'},{path:'/urunler'}]){p=page(options);p.run();assert.equal(p.opens(),0);assert.equal(p.button.hidden,true)}
p=page({blocked:true});p.run();assert.equal(p.opens(),1);p.close.onclick();p.repeat();p.run();assert.equal(p.opens(),1,'memory prevents repeated initializer auto-open when storage blocked');p.button.onclick();assert.equal(p.opens(),2);
console.log('PASS DOM-ready RAF startup, session reload suppressed, new key opens, Escape/backdrop close, explicit reopen, disabled/nonhome, blocked-storage memory');
