import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
const storefront=fs.readFileSync(new URL('../src/commerce-v2.js',import.meta.url),'utf8');
test('fresh cart catalog clears removed prices and images while preserving zero',()=>{const line=storefront.split('\n').find(x=>x.includes('function currentItem('));const p={id:'p1',name:'Fresh',effectivePrice:null,sale_price:null,list_price:null,image:''};const ctx=vm.createContext({catalog:new Map([['p1',p]]),catalogVerified:true});vm.runInContext(line,ctx);let r=ctx.currentItem({id:'p1',price:99,image:'https://old.test/image'});assert.equal(r.price,null);assert.equal(r.image,'');p.effectivePrice=0;r=ctx.currentItem({id:'p1',price:99});assert.equal(r.price,0)});
test('display distinguishes a valid zero price from no price',()=>{const ctx=vm.createContext({Intl});vm.runInContext(storefront.split('\n').find(x=>x.startsWith('function money(')),ctx);assert.match(ctx.money(0),/0,00/);assert.match(ctx.money(null),/teklif/);assert.match(ctx.money(''),/teklif/)});
const admin=fs.readFileSync(new URL('../src/zaman-admin-worker.js',import.meta.url),'utf8');const core=admin.slice(admin.indexOf('function j('),admin.indexOf('async function ensure(')).replace(/function adminProductImage[^\n]+\n/,'');const api=admin.slice(admin.indexOf('async function commerceAdminApi('),admin.indexOf('function commerceAdminPage('));
async function bulk(price,provided=true){const statements=[],ctx=vm.createContext({Headers,Response,Request,URL,crypto:webcrypto});vm.runInContext(core+'\nasync function ensure(){}\n'+api,ctx);const db={prepare(sql){return {sql,args:[],bind(...a){this.args=a;return this},async first(){return {id:'p1',name:'Test',current_price:99}},async all(){return {results:[]}}}},async batch(s){statements.push(...s);return s.map(()=>({success:true}))}};const item={id:'p1',name:'Test',active:1,featured:1,imageUrl:'',description:''};if(provided)item.price=price;const r=await ctx.commerceAdminApi(new Request('https://admin.test/api/commerce-admin/bulk-products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items:[item]})}),{DB:db},{user:{id:'owner',role:'owner'}},{});assert.equal(r.status,200);return statements}
test('bulk explicit blank removes price atomically and omitted price preserves',async()=>{let s=await bulk('');assert(s.some(x=>x.sql.startsWith('UPDATE b2b_prices')));assert(!s.some(x=>x.sql.startsWith('INSERT INTO b2b_prices')));assert(s.some(x=>x.sql.includes('b2b_price_history')&&x.args[3]===null));s=await bulk(undefined,false);assert(!s.some(x=>x.sql.includes('b2b_prices')));s=await bulk(0);assert(s.some(x=>x.sql.startsWith('INSERT INTO b2b_prices')&&x.args[2]===0))});
import {spawnSync} from 'node:child_process';
test('admin and publication price queries reject future and expired prices',()=>{const sqls=[...admin.matchAll(/\(SELECT price FROM b2b_prices_v1 pr WHERE pr\.product_id=p\.id[^\n]*?LIMIT 1\)/g)].map(x=>x[0]);assert(sqls.length>=3);const query=sqls.find(x=>x.includes('valid_until'));const code=`import sqlite3,json\nc=sqlite3.connect(':memory:')\nc.execute('CREATE TABLE b2b_prices_v1(product_id TEXT,price REAL,active INTEGER,valid_from TEXT,valid_until TEXT)')\nc.executemany('INSERT INTO b2b_prices_v1 VALUES(?,?,?,?,?)',[('p1',10,1,'2020-01-01',None),('p1',99,1,'2099-01-01',None),('p1',88,1,'2021-01-01','2022-01-01')])\nprint(c.execute('SELECT '+json.loads(${JSON.stringify(JSON.stringify(query))})+" FROM (SELECT 'p1' AS id) p").fetchone()[0])`;
const r=spawnSync('python',['-c',code],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(Number(r.stdout),10)});
